### ISSUE TITLE
Gem shouldn't require bundler

### ISSUE THREAD

**Issue by ghost** [pcreux/gitmine#1]
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- bundler (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Users/developers/.gem/ruby/1.8/gems/gitmine-0.1.0/bin/gitmine:2
    from /Users/developers/.gem/ruby/1.8/bin/gitmine:19:in `load'
    from /Users/developers/.gem/ruby/1.8/bin/gitmine:19

**Comment by jamtur01** [comment]
Ditto from - I have the same issue.

<pre>

gitmine
/usr/lib/ruby/gems/1.8/gems/bundler-0.9.21/lib/bundler/shared_helpers.rb:43:in `default_gemfile': Could not locate Gemfile (Bundler::GemfileNotFound)
    from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.21/lib/bundler/shared_helpers.rb:52:in `env_file'
    from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.21/lib/bundler.rb:148:in `env_file'
    from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.21/lib/bundler.rb:179:in `current_env_file?'
    from /usr/lib/ruby/gems/1.8/gems/bundler-0.9.21/lib/bundler.rb:99:in `load'
    from /usr/lib/ruby/gems/1.8/gems/gitmine-0.1.0/bin/gitmine:3
    from /usr/bin/gitmine:19:in `load'
    from /usr/bin/gitmine:19
</pre>

**Comment by pcreux** [comment]
Fixed in version 0.1.1. :)
